#!/usr/bin/env sh
# kısaltmalar
alias cat="pridecat" # when straight ally and you like colors
alias cls="clear"
alias vim="nvim"
alias codi="codium"
alias code="codium"
alias mkdir="mkdir -p"
alias sudo="doas" #doas btw
alias corona="curl -s https://corona-stats.online/TR|sed '5,6d'"
alias Hg="hg" #when you're chemist xD

# ayar kısayolları
alias vipico='nvim ~/.config/picom.conf'
alias vipoly="nvim ~/.config/polybar/config.ini"
alias vialias="nvim ~/.aliases"
alias vibashrc="nvim ~/.bashrc"
alias vizshrc="nvim ~/.zshrc"
alias videf="nvim ~/.definitions"
alias videfinitions="nvim ~/.definitions"

# ip ile alakalı kısayollar
alias ipa="ip a s eth0 | grep 'inet ' | sed 's+/2.*$++;s/.*t //'"
alias ipav="ip a s tun0 | grep 'inet ' | sed 's+/2.*$++;s/.*t //'"

## sübhan qedirli tarafından yapıldı - https://github.com/subhanqedirli/turkish-bash
# türkçeleştirme 
alias kök="sudo su"
alias oluştur="touch"
alias taşı="mv"
alias kopyala="cp"
alias sil="rm"
alias liste="ls"
alias çık="exit"
alias kd="cd"
alias eğer="if"
alias yaz="echo"

# sistem kısayolları
alias sleep-pc="su -c 'echo mem > /sys/power/state'"
alias sleep-pce="su -c 'echo mem > /sys/power/state'; exit"
alias yast='xdg-su -c "/sbin/yast --gtk"' #opensuse dan kalma

# shell yenileme
alias .bashrc="source ~/.bashrc"
alias .zshrc="source ~/.zshrc"
alias .aliases="source ~/.aliases"
alias .definitions="source ~/.definitions"
